export const hrComputaxFileName = 'Payroll Sample.xls';
export const hrFileStructure = {
  column: [
    'Sr no',
    'Emp Code',
    'Emp Name',
    'Department',
    'Bank A/c No',
    'Bank IFSC NO',
    'UAN',
    'ESI No',
    'Designation',
    'Bank Name',
    'Date of Joining',
    'PDays',
    'Basic Salary',
    'House Rent Allowance',
    'Other Allowances',
    'Salary Package',
    'Variable Target Incentive',
    'Arrear',
    'Gross Salary',
    'TDS',
    'Loan Installment',
    'PF Amt',
    'ESI Amt',
    'Food Advance',
    'Voluntary PF',
    'Uniform Deduction',
    'Total Deduction',
    'Net Salary Payable',
    'Employer PF',
    'Employer ESI',
    'Employer ARR PF',
    'employer CTC',
  ],
  rowIndex: 5,
};
