
export const coupons = [
    {
        couponName:"YUMNEW",
        enabled:true
    },
    {
        couponName:"ZLDWUH47ABYIQ",
        enabled:true
    },

    {
        couponName:"ZLDXHIDDDVU3I",
        enabled:true
    },
    {
        couponName:"SAVEMORE",
        enabled:true
    },
    {
        couponName:"JUST4U",
        enabled:true
    },
    {
        couponName:"TASTYTRAILS",
        enabled:true
    },
    {
        couponName:"GRAB",
        enabled:true
    },
    {
        couponName:"TREATNEW",
        enabled:true
    },
    {
        couponName:"ZLDS2S03M2MIE",
        enabled:true
    },
    {
        couponName:"ONLY4U",
        enabled:true
    },
    {
        couponName:"TRYTHIS",
        enabled:true
    },
    {
        couponName:"OZRFH9P68R9Q",
        enabled:true
    },
    {
        couponName:"OZT5S2ERN84E",
        enabled:true
    },
    {
        couponName:"BINGE",
        enabled:true
    },
    {
        couponName:"SOMETHINGNEW",
        enabled:true
    },
    {
        couponName:"ZRNKCTWOROXR",
        enabled:true
    },
    {
        couponName:"ZTREAT",
        enabled:true
    },
    {
        couponName:"ZRQHQRUGEPDB",
        enabled:true
    },
    {
        couponName:"GET125OFF",
        enabled:true
    },
    {
        couponName:"ZRGKBWMMPCAJ",
        enabled:true
    },
    {
        couponName:"ZLDWZM14ZKNRU",
        enabled:true
    },
    {
        couponName:"ZRFYHYMCOJMD",
        enabled:true
    },
    {
        couponName:"ICICICC",
        enabled:true
    },
    {
        couponName:"ZRUMJEUGNCGM",
        enabled:true
    },
    {
        couponName:"ICICIAPAY",
        enabled:true
    },
    {
        couponName:"ICICIAPAYNEW",
        enabled:true
    },
    {
        couponName:"PAYTMFEAST",
        enabled:true
    },
    {
        couponName:"ZLDVU1AXB5Z9Y",
        enabled:true
    },
    {
        couponName:"ZOMPAYTM",
        enabled:true
    },
    {
        couponName:"AXISNEO",
        enabled:true
    },
    {
        couponName:"ZLD3KS9H7BK2M",
        enabled:true
    },
    {
        couponName:"ZLD3KS9H7BK2M",
        enabled:true
    },
    {
        couponName:"ZRVYNRSXYFEH",
        enabled:true
    },
    {
        couponName:"PAYTMWEEKEND",
        enabled:true
    },
    {
        couponName:"ZRYMOWKBRDEH",
        enabled:true
    },
    {
        couponName:"ZLDUAH7UA2XWI",
        enabled:true
    },
    {
        couponName:"OZQXIRKOGVZE",
        enabled:true
    },
    {
        couponName:"SIMPLPARTY",
        enabled:true
    },
    {
        couponName:"PPNEW",
        enabled:true
    },
    {
        couponName:"ZOYUMMY",
        enabled:true
    },
    {
        couponName:"EATNEW",
        enabled:true
    },
    {
        couponName:"ZROGCWZULXAS",
        enabled:true
    },
    {
        couponName:"ZRWFBTILYQMW",
        enabled:true
    },
    {
        couponName:"AUCC100",
        enabled:true
    },
    {
        couponName:"OZQP5A5706X2",
        enabled:true
    },
    {
        couponName:"ICICIDC",
        enabled:true
    },
    {
        couponName:"ZLDRTPGD2Z02U",
        enabled:true
    },
    {
        couponName:"ZRKAYZTMMKVS",
        enabled:true
    },
    {
        couponName:"KOTAKWEEKENDDC",
        enabled:true
    },
    {
        couponName:"HUNGER",
        enabled:true
    },
    {
        couponName:"HSBCDELIGHTS",
        enabled:true
    },
    {
        couponName:"ZLDYNX9MV1MYU",
        enabled:true
    },
    {
        couponName:"CREDTREATS",
        enabled:true
    },
    {
        couponName:"DISCOVER",
        enabled:true
    },
    {
        couponName:"ZLDZCD5PZX39Y",
        enabled:true
    },
    {
        couponName:"ZRXVQWISNJST",
        enabled:true
    },
    {
        couponName:"CRAVENEW",
        enabled:true
    },
    {
        couponName:"TEMPTATION",
        enabled:true
    },
    {
        couponName:"ZRKGGQAZKONY",
        enabled:true
    },
    {
        couponName:"ZRHIIAXSSDPE",
        enabled:true
    },
    {
        couponName:"SBITREATS",
        enabled:true
    },
    {
        couponName:"ZRSKOSRGSOFV",
        enabled:true
    },
    {
        couponName:"ZRISQVQFVULV",
        enabled:true
    },
    {
        couponName:"DELICIOUS",
        enabled:true
    },
    {
        couponName:"TASTENEW",
        enabled:true
    },
    {
        couponName:"ICICIDCNEW",
        enabled:true
    },
    {
        couponName:"DELISH",
        enabled:true
    },
    {
        couponName:"ZREQYBGSBBDD",
        enabled:true
    },
    {
        couponName:"CRAVE",
        enabled:true
    },
    {
        couponName:"ZRNKYCYVHODV",
        enabled:true
    },
    {
        couponName:"ZRSIWIBHCAJI",
        enabled:true
    },
]







