export const allowedFileNames: string[] = [
  'Item_Report_With_Customer_Order.xlsx',
  'Order_Audit_Item_Wise.xlsx',
  'Orders_Master_Report.xlsx',
  'Order_Modification_Reports.xlsx',
  'Order_Report_payment_wise.xlsx',
  'Dis_Orders_summary.xlsx',
  'Zomato.xlsx',
  'Swiggy.xlsx',
  'sale_report_online_platforms.xlsx',
];
export const PetPoojaAllowedFileNames: string[] = [
  'Item_Report_With_Customer_Order',
  'Order_Audit_Item_Wise',
  'Orders_Master_Report',
  'Order_Modification_Reports',
  'Order_Report_payment_wise',
  'Dis_Orders_summary',
  'Zomato',
  'Swiggy',
  'sale_report_online_platforms',
];
export const PetPoojaAllowedFileNamesWithStartingRowIndex = [
  { fileName: 'Item_Report_With_Customer_Order', startingRowIndex: 6 },
  { fileName: 'Order_Audit_Item_Wise', startingRowIndex: 5 },
  { fileName: 'Orders_Master_Report', startingRowIndex: 10 },
  { fileName: 'Order_Modification_Reports', startingRowIndex: 5 },
  { fileName: 'Order_Report_payment_wise', startingRowIndex: 9 },
  { fileName: 'Dis_Orders_summary', startingRowIndex: 3 },
  { fileName: 'Zomato', startingRowIndex: 1 },
  { fileName: 'Swiggy', startingRowIndex: 1 },
  { fileName: 'sale_report_online_platforms', startingRowIndex: 5 },
];

export const petPoojaFilesStructure = {
  Item_Report_With_Customer_Order: {
    column: [
      'Date',
      'Invoice No.',
      'Item Name',
      'Order Type',
      'Price',
      'Qty.',
      'Sub Total',
      'Discount',
      'Tax',
      'Final Total',
      'Status',
      'Table No.',
      'Server Name',
      'Covers',
      'Variation',
      'Category',
      // 'HSN',
      // 'Assign To',
      'Non Taxable',
      'CGST Rate',
      'CGST Amount',
      'SGST Rate',
      'SGST Amount',
      'VAT Rate',
      'VAT Amount',
    ],
    rowIndex: 4,
  },
  Order_Audit_Item_Wise: {
    column: ['Invoice No.', 'Item Modified Date', 'Order Type', 'By User', 'Old Value', 'New Value', 'Item Status', 'When', 'Reason'],
    rowIndex: 4,
  },
  Orders_Master_Report: {
    column: [
      'Invoice No.',
      'Date',
      'Biller',
      // 'KOT No.',
      'Payment Type',
      'Order Type',
      'Status',
      'Area',
      'Sub Order Type',
      'Group Name',
      'GSTIN',
      // 'Assign To',
      'Order Cancel Reason',
      'My Amount (₹)',
      'Discount (₹)',
      'Net Sales (₹)(M.A - D)',
      'Delivery Charge',
      'Container Charge',
      'Service Charge',
      'Total Tax (₹)',
      'Round Off',
      'Waived off',
      'Total (₹)',
      'Online Tax Calculated',
      'GST Paid by Merchant',
      'GST Paid by Ecommerce',
      'Tip (₹)',
      'Non Taxable',
      'Amount (CGST)',
      'CGST',
      'Amount (SGST)',
      'SGST',
      'Amount (VAT)',
      'VAT',
    ],
    rowIndex: 4,
  },
  Order_Modification_Reports: {
    column: ['Invoice No.', 'Date', 'Change Log'],
    rowIndex: 4,
  },
  Order_Report_payment_wise: {
    column: ['Invoice No.', 'Cash', 'Order Type', 'Date', 'Payment Type', 'Card', 'Due Payment', 'Other', 'Wallet', 'Online'],
    rowIndex: 4,
  },
  Dis_Orders_summary: {
    column: ['Created Date', 'Order No.', 'Order Type', 'Coupon', 'Discount', 'Reason'],
    rowIndex: 2,
  },
  Zomato: {
    column: ['Invoice No.', 'Date', 'Order Type', 'Area', 'Status', 'Name', 'Order Cancel Reason'],
    rowIndex: 0,
  },
  Swiggy: {
    column: ['Invoice No.', 'Date', 'Order Type', 'Area', 'Status', 'Name', 'Order Cancel Reason'],
    rowIndex: 0,
  },
  sale_report_online_platforms: {
    column: ['Date', 'Client Order No.', 'Order From', 'Virtual Brand Name', 'Total (₹)', 'Invoice No.'],
    rowIndex: 3,
  },
};
